name = "backend"
compatibility_date = "2023-12-01"

 [vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNGE1ZjI5NmYtYWExYi00ZTEzLTg4MTQtY2VhNGVjNDc1NTQ1IiwidGVuYW50X2lkIjoiNTgwM2VmOGVhZDdmOTRjODI4NmY1MDVkOGU3ZTIzZGI1MjliMjQ0Yzk4NTIzN2I2YjYzNTFiYTAyZjU3ODQ3NSIsImludGVybmFsX3NlY3JldCI6Ijg2YWE3Y2UzLWUyNDctNDVlZi04Mzg4LTE2NWRiZTZlNTAzMCJ9.dBM08j29S_h-fgn3MDB4BmG5osixFWep6cEl0uEKEmU"

# MY_VAR = "my-variable"
JWT_SECRET="provenworks"